M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu20.04.1} date lun. 12 juin 2023 15:09:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-12T15:09:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.800
%
G90
G05
T1
X47.55Y-179.68
X136.45Y-179.68
T0
M30
